easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Page
        - App\Entity\Template
    design:
        assets:
            css:
                - 'libs/codemirror/lib/codemirror.css'
                - 'libs/codemirror/theme/material.css'
                - 'libs/codemirror/addon/display/fullscreen.css'
                - 'build/css/admin.css'
            js:
                - 'build/js/admin.js'
                - 'libs/codemirror/lib/codemirror.js'
                - 'libs/codemirror/mode/javascript/javascript.js'
                - 'libs/codemirror/mode/css/css.js'
                - 'libs/codemirror/mode/xml/xml.js'
                - 'libs/codemirror/mode/htmlmixed/htmlmixed.js'
                - 'libs/codemirror/addon/display/fullscreen.js'