version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - ./docker/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
      - ./docker/logs:/var/www/logs
      - .:/var/www/html


  mysql:
    image: mariadb:10.3.2
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: anthonykgrossfr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306