anthonykgrossfr:
  image: registry.gitlab.com/anthonykgross/akg-anthonykgrossfr:master
  volumes:
    - ./conf/php5:/etc/php5
    - ./conf/supervisor:/etc/supervisor/conf.d
    - ./conf/nginx:/etc/nginx
    - ./src:/src
    - ./logs:/logs
  environment:
    VIRTUAL_HOST: "anthonykgross.fr,anthonykgross.local"
