parameters:
#    anthonykgrossfr_main.example.class: Anthonykgrossfr\MainBundle\Example

services:
#    anthonykgrossfr_main.example:
#        class: %anthonykgrossfr_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
