name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: anthonykgross/ansible-vault-cli-github-action@v1
      with:
        vault_key: ${{ secrets.vault_key }}
        command: 'ansible-vault decrypt ENV && chown 1001:116 ENV && chmod +r ENV'

    - name: Set the value
      run: cat ENV >> $GITHUB_ENV

    - name: Set the value
      run: printenv

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: anthonykgross/anthonykgrossfr:latest
        build-args: |
          APPLICATION_ENV=prod
          MAILER_USER=${{ env.MAILER_USER }}
          MAILER_PASSWORD=${{ env.MAILER_PASSWORD }}
          DB_USER=${{ env.DB_USER }}
          DB_PASSWORD=${{ env.DB_PASSWORD }}
          DB_HOST=${{ env.DB_HOST }}
          DB_NAME=${{ env.DB_NAME }}
          ALGOLIA_APP_ID=${{ env.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY=${{ env.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_API_KEY=${{ env.ALGOLIA_API_KEY }}
          ADMIN_USER=${{ env.ADMIN_USER }}
          ADMIN_SHA512_PASSWORD=${{ env.ADMIN_SHA512_PASSWORD }}