name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: anthonykgross/ansible-vault-cli-github-action@v1
      with:
        vault_key: ${{ secrets.vault_key }}
        command: 'ansible-vault decrypt ENV'

    - name: Set the value
      run: ls -al

    - name: Set the value
      run: printenv

#    - name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: docker/Dockerfile
#        push: true
#        tags: anthonykgross/anthonykgrossfr:latest
#        build-args: |
#          APPLICATION_ENV=prod
#          MAILER_USER=${{secrets.MAILER_USER}}
#          MAILER_PASSWORD=${{secrets.MAILER_PASSWORD}}
#          DB_USER=${{secrets.DB_USER}}
#          DB_PASSWORD=${{secrets.DB_PASSWORD}}
#          DB_HOST=${{secrets.DB_HOST}}
#          DB_NAME=${{secrets.DB_NAME}}
#          ALGOLIA_APP_ID=${{secrets.ALGOLIA_APP_ID}}
#          ALGOLIA_ADMIN_KEY=${{secrets.ALGOLIA_ADMIN_KEY}}
#          ALGOLIA_API_KEY=${{secrets.ALGOLIA_API_KEY}}
#          ADMIN_USER=${{secrets.ADMIN_USER}}
#          ADMIN_SHA512_PASSWORD=${{secrets.ADMIN_SHA512_PASSWORD}}