name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: anthonykgross/anthonykgrossfr:latest
        build-args: |
          APPLICATION_ENV=prod
          VAULT_KEY=${{ secrets.vault_key }}

    - uses: addnab/docker-run-action@v1
      with:
        image: cdrx/rancher-gitlab-deploy
        run: upgrade --environment ${{ secrets.RANCHER_ENV }} --stack ${{ secrets.RANCHER_STACK }} --service ${{ secrets.RANCHER_SERVICE }} --no-start-before-stopping --no-wait-for-upgrade-to-finish
